### ISSUE TITLE
Error with new update v2.1.3

### ISSUE THREAD

**Issue by Mick51** [denysdovhan/purifier-card#106]
![Capture d’écran 2022-04-20 230342](https://user-images.githubusercontent.com/40418405/164322702-25be7f5c-ec0d-4872-871d-c545ea3a0058.jpg)

## System Health

version | core-2022.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3674
Installed Version | 1.24.5
Stage | running
Available Repositories | 1097
Downloaded Repositories | 45

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 111.1 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.14.0), File editor (5.3.3), RPC Shutdown (2.2), Samba share (9.5.1), Home Assistant Google Drive Backup (0.106.2), Terminal & SSH (9.3.0), Glances (0.15.0), Check Home Assistant configuration (3.10.0), SQLite Web (3.3.0), ESPHome (2022.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 33
views | 9
mode | storage

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.5.6
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 5
added_devices | 2

</details>

**Comment by Microbeen** [comment]
I have a similar problem

**Comment by V4n1X** [comment]
Same here

**Comment by zz66** [comment]
yes me too

**Comment by denysdovhan** [comment]
Same problem here: https://github.com/denysdovhan/vacuum-card/issues/366

Can't figure out the problem. Any help is appretiated.
