### ISSUE TITLE
purifier-card.js?hacstag=274738925222:1 Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by majkers** [denysdovhan/purifier-card#109]
I just update to latest v.2.2.2 via latest HACS and my card stopped working with message:

"Custom element doesn't exist: purifier-card." and i JS console I see

```
purifier-card.js?hacstag=274738925222:1 Uncaught ReferenceError: regeneratorRuntime is not defined
    at purifier-card.js?hacstag=274738925222:1:22296
    at purifier-card.js?hacstag=274738925222:1:23186
```

**Steps to reproduce**

Just open ha page...

**Expected behavior**

I should see my card

**Versions:**

- Release: 2.2.2
- Browser:Chrome, Edge, all.....
- HomeAssistant version: 2022.4.7

**Comment by AlexSanti** [comment]
Same error here, Updated today

**Comment by pozek** [comment]
After last update
Custom element doesn't exist: purifier-card
type: custom:purifier-card
entity: fan.xxxxxxxxxxxxx
compact_view: false

**Comment by bobloadmire** [comment]
thank god it's not just me, was pulling my hair out

**Comment by denysdovhan** [comment]
the issue should be resolved by the latest release

**Comment by CumpsD** [comment]
Seems to be back with 2.3.0? Downgrading to 2.2.3 fixes it.
