### ISSUE TITLE
Error resolving module specifier “lit”

### ISSUE THREAD

**Issue by bjeanes** [denysdovhan/purifier-card#123]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

Purifier card "does not exist" according to lovelace and error in logs from the .js file

Logs:

```
https://[MYINSTANCE]/hacsfiles/purifier-card/purifier-card.js?hacstag=274738925223:1:42 TypeError: Error resolving module specifier “lit”. Relative module specifiers must start with “./”, “../” or “/”.
```

**Screenshots**

![Screen Shot 2022-05-10 at 1 17 47 pm](https://user-images.githubusercontent.com/2560/167535862-14f02ba5-52f6-4e1d-bbf6-c1beae9934c6.png)

**Versions:**

- Release: 2.2.3
- Browser: FF developer edition 101.0b4 (64-bit)
- HomeAssistant version: 2022.5.2

**Comment by najdanovicivan** [comment]
This is not an issue. You're trying to use uncompiled js file. The sources have to be compiled with
`npm run-script build` and then use the js from the dist directory
