### ISSUE TITLE
AQI -> µg/m³ or PM2.5

### ISSUE THREAD

**Issue by Dany74PL** [denysdovhan/purifier-card#15]
Can you please add the possibility to change the value description in the middle? Air Purifier 2 provides PM2.5, not AQI, which is confusing.

**Comment by denysdovhan** [comment]
This has to be a pretty easy change. You're welcome to open a PR!

**Comment by Dany74PL** [comment]
I wish I knew how to do it...

**Comment by denysdovhan** [comment]
Already implemented
