### ISSUE TITLE
Background color according to AQI level

### ISSUE THREAD

**Issue by potat0man** [denysdovhan/purifier-card#16]
Card background is --primary-color which is too bright in dark theme
![before](https://user-images.githubusercontent.com/67843546/95931735-a8219b00-0dd2-11eb-80c0-053d66d31ff9.PNG)

My solution to fit theme is to change background color (line 245) to --card-background-color this way it fits dark theme
![after](https://user-images.githubusercontent.com/67843546/95931745-aa83f500-0dd2-11eb-93d8-39e85b8c47b4.PNG)

Better idea is to make dark part of AQI background color, according to AQI level, like: green when its ok, yellow when medium and red when dark

**Comment by akarpych** [comment]
> Card background is --primary-color which is too bright in dark theme
> ![before](https://user-images.githubusercontent.com/67843546/95931735-a8219b00-0dd2-11eb-80c0-053d66d31ff9.PNG)
> 
> My solution to fit theme is to change background color (line 245) to --card-background-color this way it fits dark theme
> ![after](https://user-images.githubusercontent.com/67843546/95931745-aa83f500-0dd2-11eb-93d8-39e85b8c47b4.PNG)
> 
> Better idea is to make dark part of AQI background color, according to AQI level, like: green when its ok, yellow when medium and red when dark

Can you tell us more about how you did it?

**Comment by phyrz91** [comment]
@potat0man  Can you share what exactly you replace in the file? Thank you in advance.

**Comment by potat0man** [comment]
> @potat0man Can you share what exactly you replace in the file? Thank you in advance.

edit file \www\community\purifier-card\purifier-card.js
change line #245 from this:
    background-color: var(--primary-color);
to this:
    background-color: var(--card-background-color);
then delete purifier-card.js.gz file and refresh

**Comment by mouth4war** [comment]
I think making the background consistent with other standard cards should be merged. It should also make card work with transparent themes.
