### ISSUE TITLE
Can't translate "Idle" mode

### ISSUE THREAD

**Issue by andriej** [denysdovhan/purifier-card#18]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

"Idle" is not available in translation file, thus can't be translated as other modes.

**Steps to reproduce**

Switch language to non-english

**Expected behavior**
Should be translateable as other speeds

**Screenshots**
![image](https://user-images.githubusercontent.com/6303489/98279636-7dbe9a00-1f9a-11eb-9a68-35c754e4350a.png)

**Versions:**

- Release: 0.5.0
- Browser: chrome
- HomeAssistant version: 0.117.3

**Comment by denysdovhan** [comment]
Just add a corresponding key in the translation file.
