### ISSUE TITLE
The remaining time is not displayed

### ISSUE THREAD

**Issue by trancer86** [denysdovhan/purifier-card#212]
Hello. I integrated my air purifier into home assistant. I used your card and I can say that everything works, I don't get any errors. I have no problem with management, all sensors and automation work correctly. The only problem I can't solve is that the expiring life time of the filler is not displayed correctly. Can you tell me how to solve this problem?

**Card Configuration:**
type: custom:purifier-card
entity: fan.xiaomi_smart_air_purifier_4_pro
aqi:
  entity_id: sensor.xiaomi_smart_air_purifier_4_pro_pm2_5
  unit: µg/m³
stats:
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_filter_life_remaining
    unit: '%'
    subtitle: Filter Remaining
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_motor_speed
    unit: RPM
    subtitle: Motor Speed
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_filter_time_left
    value_template: '{{ (value | float(0) / 3600) | round(1) }}'
    unit: hours
    subtitle: Filter Life
shortcuts:
  - name: Silent
    icon: mdi:weather-night
    preset_mode: Silent
  - name: 25%
    icon: mdi:circle-slice-2
    percentage: 25
  - name: 50%
    icon: mdi:circle-slice-4
    percentage: 50
  - name: 75%
    icon: mdi:circle-slice-6
    percentage: 75
  - name: 100%
    icon: mdi:circle-slice-8
    percentage: 100
  - name: Auto
    icon: mdi:brightness-auto
    preset_mode: Auto
show_name: true
show_state: true
show_toolbar: true
compact_view: false
______________________
**Screenshots**
![IMG_20230124_105441](https://user-images.githubusercontent.com/89747460/214249546-7d18ee34-781e-4640-85b0-e54405cae936.jpg)

**Versions:**

- Release: [2.2.3]
- Browser: [chrome]
- HomeAssistant version: [2023.1.6]

**Comment by alamoudimoh** [comment]
same here with 3H

**Comment by PPsyrius** [comment]
AFAIK the default `_time_left` sensor seems to default to days instead of hours for this widget for some reason
```yml
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_filter_time_left
    unit: Days
    subtitle: Left
```
![image](https://github.com/denysdovhan/purifier-card/assets/19505219/c37cbe2a-ab8c-431e-b0c2-5c12caea4461)
![image](https://github.com/denysdovhan/purifier-card/assets/19505219/7686c0ef-4a31-488a-a024-1c047640d14c)
