### ISSUE TITLE
Make component/service domain configurable

### ISSUE THREAD

**Issue by syssi** [denysdovhan/purifier-card#22]
**Is your feature request related to a problem? Please describe.**

I don't use the offical `xiaomi_miio` component of HA. The custom component is called `xiaomi_miio_airpurifier` (https://github.com/syssi/xiaomi_airpurifier). If I try to use custom actions like:

```
  - name: 25%
    icon: 'mdi:circle-slice-2'
    speed: Favorite
    xiaomi_miio_favorite_level: 3
```

This error is returned:

Error calling the service xiaomi_miio/fan_set_favorite_level. Service not found.

The service is called `xiaomi_miio_airpurifier.fan_set_favorite_level`. 

**Describe the solution you'd like**

Make the service domain configurable:

https://github.com/denysdovhan/purifier-card/blob/master/src/purifier-card.js#L287

**Describe alternatives you've considered**

Autodetect the service domain.

**Comment by akarpych** [comment]
simply replacing xiaomi_miio.fan_set_favorite_level with xiaomi_miio_airpurifier.fan_set_favorite_level doesn't help?

**Comment by akarpych** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I don't use the offical `xiaomi_miio` component of HA. The custom component is called `xiaomi_miio_airpurifier` (https://github.com/syssi/xiaomi_airpurifier). If I try to use custom actions like:
> 
> ```
>   - name: 25%
>     icon: 'mdi:circle-slice-2'
>     speed: Favorite
>     xiaomi_miio_favorite_level: 3
> ```
> 
> This error is returned:
> 
> Error calling the service xiaomi_miio/fan_set_favorite_level. Service not found.
> 
> The service is called `xiaomi_miio_airpurifier.fan_set_favorite_level`. 
> 
> **Describe the solution you'd like**
> 
> Make the service domain configurable:
> 
> https://github.com/denysdovhan/purifier-card/blob/master/src/purifier-card.js#L287
> 
> **Describe alternatives you've considered**
> 
> Autodetect the service domain.
> 

simply replacing xiaomi_miio.fan_set_favorite_level with xiaomi_miio_airpurifier.fan_set_favorite_level doesn't help?

**Comment by syssi** [comment]
Editing helps but isn't a proper solution.

**Comment by akarpych** [comment]
> Editing helps but isn't a proper solution.


after I changed the service in the script, nothing changed for me. Tell me what else needs to be changed?

**Comment by denysdovhan** [comment]
It is configurable. You should use `platform` option.
