### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by tOOmki** [denysdovhan/purifier-card#228]
In the HA logs I have this error:
"Uncaught ReferenceError: regeneratorRuntime is not defined"
Card not showing - "Custom element doesn't exist: purifier-card."
Version 2.3.0

Home Assistant 2023.6.1
Supervisor 2023.06.2
Operating System 10.2
Interfejs użytkownika: 20230608.0 - latest

**Comment by ckhericks** [comment]
Same, it appears as though card 'custom:purifier-card' is no longer found in lovelace after updating to 2.3.0?

**Comment by gabrymed** [comment]
Same here with 3H.

**Comment by denysdovhan** [comment]
Hey, that's my mistake. I released a version with updated dependencies, one of those were broken. The fix is coming right now.

**Comment by gabrymed** [comment]
@denysdovhan 
Thanks a lot

**Comment by oopiicaa** [comment]
It's still the same in 2.3.1

**Comment by stephywephy88** [comment]
> It's still the same in 2.3.1

My cards are back up 👍🏼

**Comment by spider7611** [comment]
2.3.1 not working for me, must go back to 2.2.3 which is working ok.
