### ISSUE TITLE
Card not available

### ISSUE THREAD

**Issue by Magix3D** [denysdovhan/purifier-card#230]
**Before submitting a bug**

✅ I updated to the latest version available
✅ I cleared the cache of my browser

**Describe the bug**

I tried both, installing it via HACS and manually, neither of those options worked.

I tried both multiple times, I coudn't get the card to show or the yaml-config-card to work, bc. it says the card isn't available.

I restarted to whole HA, cleared the browser data. Every other card works fine. Is there maybe a problem witht the latest HA version?

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: 2.3.1
- Browser: Chrome
- HomeAssistant version: 2023.6.2

**Comment by pavolcizmarik** [comment]
Same here, vacuum card is working just fine.

**Comment by denysdovhan** [comment]
Please, try the latest version. Should be fixed in there.

Pleaes don't forget to hard-reload your browser with cleaning the cache.

**Comment by Magix3D** [comment]
> Please, try the latest version. Should be fixed in there.
> 
> Pleaes don't forget to hard-reload your browser with cleaning the cache.

Hey, not with me, problem still persists.
