### ISSUE TITLE
custom elements doesn't exist: purifier-card

### ISSUE THREAD

**Issue by Sygnus83** [denysdovhan/purifier-card#232]
[ ] I updated to the latest version available
[ ] I cleared the cache of my browser

After update i have this errro on lovelac card :

custom elements doesn't exist: purifier-card

I try reinstall in HACS , try older . Try add manual but not working, all time this error .

![image](https://github.com/denysdovhan/purifier-card/assets/92396929/40f2bedc-fef6-4a54-b236-5b6c86dc45ec)

**Comment by spider7611** [comment]
Have the sam problem. When I go back to 2.2.3 working good. After all of version have the same problem.

**Comment by Sygnus83** [comment]
> Have the sam problem. When I go back to 2.2.3 working good. After all of version have the same problem.

Thanks, 2.2.3 working for me !

**Comment by alexanderznamensky** [comment]
The same problem as well, even v2.2.3 is not working.
But if I installe on the fresh instatce (where I didn't install purified-card before) - everiting is OK.
There are all required files in /config/www/community/purifier-card/:
![image](https://github.com/denysdovhan/purifier-card/assets/65254375/4d714679-df90-4353-b6dd-0ef563a38e50)
Also there is the resourse sourse:
![image](https://github.com/denysdovhan/purifier-card/assets/65254375/63f4f31f-efce-4e64-89d8-bde36f305e5f)
In the mean time, card is not eisitng in UI:
![image](https://github.com/denysdovhan/purifier-card/assets/65254375/e23f5193-ce5e-45e2-a784-a436742dca86)

**Comment by leovape** [comment]
The same here.

**Comment by 00punisher** [comment]
Same here with latest version... it worked but stopped working after updating. Coming back to 2.2.3 does not work.

**Comment by bobloadmire** [comment]
Same

**Comment by leppa** [comment]
The console error (`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "ha-template" has already been used with this registry`) is exactly the same as in the Landroid Card bug Barma-lej/landroid-card#163. There's [a comment](https://github.com/Barma-lej/landroid-card/issues/163#issuecomment-1596009963) that it's a conflict with the `vacuum-card`.
There's also a fix, maybe the same approach can be used with this card?

**Comment by alexanderznamensky** [comment]
> The console error (`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "ha-template" has already been used with this registry`) is exactly the same as in the Landroid Card bug [Barma-lej/landroid-card#163](https://github.com/Barma-lej/landroid-card/issues/163). There's [a comment](https://github.com/Barma-lej/landroid-card/issues/163#issuecomment-1596009963) that it's a conflict with the `vacuum-card`. There's also a fix, maybe the same approach can be used with this card?

I can confirme - without vacuum card installed everything is working OK with v2.4.0 of purifier card.

**Comment by 00punisher** [comment]
I can confirm I have the vacuum-card installed. Thanks!

**Comment by DannyFeliz** [comment]
I just removed the vacuum card and it worked.

**Comment by Sygnus83** [comment]
But, now this its the problem...

![image](https://github.com/denysdovhan/purifier-card/assets/92396929/f7cce1a3-f7b2-49c0-b27d-f9ff50ca7d27)
