### ISSUE TITLE
Card-mod not working

### ISSUE THREAD

**Issue by Gh61** [denysdovhan/purifier-card#234]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

Since version 2.4.0 the [card-mod](https://github.com/thomasloven/lovelace-card-mod) is not working.

**Steps to reproduce**

1. try edit your card
2. add `card_mod: style:` or `style:` attribute and create some style
3. style is not applied (card mod's style tag is empty in rendered component)

**Expected behavior**

It should work.

**Screenshots**
No errors in console.

**Versions:**

- Release: since 2.4.0 (is working in 2.3.1)

**Note**
I had the same problem when developing my custom card.
The card-mod relay on `config` property on card instance. I was maping passed config to my custom config object (thus the `card_mod` or `style` values was lost and card_mod was not rendering anything).

**Comment by gh0stp1rate** [comment]
same here. Thought it was just me. Been driving me nuts for a few weeks!

**Comment by Lampyridae1984** [comment]
+1

**Comment by Gh61** [comment]
Still not solved.

**Comment by chinswain** [comment]
How do we apply the fix from your pull request @Gh61?

**Comment by Gh61** [comment]
The owner of the repo needs to review the pull request and in case that everything is alright, He can accept it and merge to the project.
Sadly he isn't quite active lately. We just have to wait.

**Comment by Gh61** [comment]
Hi @denysdovhan,

I am waiting with update for card-mod to be working again.
Can you please take a look at my [Pull request #247](https://github.com/denysdovhan/purifier-card/pull/247) and let me know if I should change anything.

Thank you again for your work on this beautiful card.

**Comment by Gh61** [comment]
Issue resolved in [v2.5.1](https://github.com/denysdovhan/purifier-card/releases/tag/v2.5.1)
