### ISSUE TITLE
Stats not displaying from other entity

### ISSUE THREAD

**Issue by codylv7** [denysdovhan/purifier-card#30]
[X] I updated to the latest version available
[X] I cleared the cache of my browser

Stats do not display when attribute is from entity other than fan.

1. Open config
2. Add stats to purifier card from another entity (air_quality.master_bedroom_dyson is what I am using)
3. Card displays UOM and Subtitle but not the attribute

Expect it to show attribute value from air_quality entity.

![Screenshot 2021-01-09 142711](https://user-images.githubusercontent.com/40413816/104109866-f259d180-5286-11eb-8419-03c01264845c.png)
![Screenshot 2021-01-09 142731](https://user-images.githubusercontent.com/40413816/104109868-f554c200-5286-11eb-9028-d6d535025086.png)

- Release: 0.6.1
- Browser: Chrome
- HomeAssistant version: 2021.1.1

**Comment by denysdovhan** [comment]
You can specify either `entity_id` or `attribute`.

**Comment by codylv7** [comment]
I changed my config to only entity and now the stats have disappeared completely..
![2021-03-17_20-30-18](https://user-images.githubusercontent.com/40413816/111569346-ad0ec000-875f-11eb-8042-0ad90e65c04c.png)
![2021-03-17_20-30-35](https://user-images.githubusercontent.com/40413816/111569353-b13add80-875f-11eb-86c2-4ea4819d7d97.png)
