### ISSUE TITLE
Request Support for Xiaomi Air Purifier 4 Lite

### ISSUE THREAD

**Issue by mrkaqz** [denysdovhan/purifier-card#302]
Please support support for Xiaomi Air Purifier 4 Lite.
The card works most of the function now except fan slider level

**Comment by lageorgem** [comment]
+1 on this. This purifier doesn't appear to have the service for changing fan levels. Instead, the fan level can be manually set on the Favorite preset.
The solution would be either to switch to the Favorite preset and change its value (if possible), or to simply hide the fan slider on this model.
