### ISSUE TITLE
Basic image of the complement

### ISSUE THREAD

**Issue by kilem86** [denysdovhan/purifier-card#310]
I have installed the complement since long time ago to control my air purifier, but since.... near to a year ago, the plugin is not showing me info about the motor speed, the PM2.5 detail, or filter life remaining. I have this code into my lovelace:

type: custom:purifier-card
entity: fan.come_peos_profesional
aqi: sensor.come_peos_profesional_pm2_5
attribute: sensor.come_peos_profesional_pm2_5
Unit: µg/m³
stats:
  - attribute: come_peos_profesional_filter_life_remaining
    unit: '%'
    subtitle: Filtro Restante
  - attribute: sensor.come_peos_profesional_motor_speed
    unit: RPS
    subtitle: Velocidad Motor
shortcuts:
  - name: Silent
    icon: mdi:weather-night
    speed: Silent
  - name: 25%
    icon: mdi:circle-slice-2
    speed: Favorite
    xiaomi_miio_favorite_level: 3
  - name: 50%
    icon: mdi:circle-slice-4
    speed: Favorite
    xiaomi_miio_favorite_level: 7
  - name: 75%
    icon: mdi:circle-slice-6
    speed: Favorite
    xiaomi_miio_favorite_level: 10
  - name: 100%
    icon: mdi:circle-slice-8
    speed: Favorite
    xiaomi_miio_favorite_level: 14
  - name: Auto
    icon: mdi:brightness-auto
    speed: Auto
show_name: true
show_state: true
show_toolbar: true
compact_view: false

That should provide me some info about the speed of motor, filter life remaining, and more, but I only see this in lovelace:

![purificador fallo](https://github.com/denysdovhan/purifier-card/assets/74058057/7f59c132-1227-4c24-b9be-d91b0f3acc2c)
![purificador fallo2](https://github.com/denysdovhan/purifier-card/assets/74058057/fdeb7dcb-c432-4e04-b326-1bd3a8d6d57f)

I have updated the Home assistant with all updates. And I dont know if something wrong with my configuration, or something that happen to everyone who use this plugin.

The problem appear in Google Chrome, and also Android Home assistant app

**Comment by kilem86** [comment]
Extra info: my device is: 

zhimi.airpurifier.ma4
por Xiaomi

provided by Xiaomi Miio integration, maybe this is the problem that I have.... I dont know
![purificador fallo3](https://github.com/denysdovhan/purifier-card/assets/74058057/ddeb6606-4ab1-4ef4-854b-d39fc8f1348f)
![purificador fallo4](https://github.com/denysdovhan/purifier-card/assets/74058057/6424b7cd-f54f-4c92-b47a-356a67342854)

**Comment by kilem86** [comment]
Solved.

Finally the correct  code to make everything works again is:

type: custom:purifier-card
entity: fan.come_peos_profesional
aqi:
  entity_id: sensor.come_peos_profesional_pm2_5
  Unit: µg/m³
stats:
  - entity_id: sensor.come_peos_profesional_motor_speed
    unit: RPM
    subtitle: Velocidad Motor
  - entity_id: sensor.come_peos_profesional_filter_life_remaining
    unit: '%'
    subtitle: Filtro Restante
  - entity_id: sensor.come_peos_profesional_filter_use
    unit: horas
    subtitle: Vida del Filtro
shortcuts:
  - name: Silent
    icon: mdi:weather-night
    preset_mode: Silent
  - name: 25%
    icon: mdi:circle-slice-2
    percentage: 25
  - name: 50%
    icon: mdi:circle-slice-4
    percentage: 50
  - name: 75%
    icon: mdi:circle-slice-6
    percentage: 75
  - name: 100%
    icon: mdi:circle-slice-8
    percentage: 100
  - name: Auto
    icon: mdi:brightness-auto
    preset_mode: Auto
show_name: true
show_state: true
show_toolbar: true
compact_view: false


I changed "attibute" for "entity_id"

![purificador fallo5](https://github.com/denysdovhan/purifier-card/assets/74058057/77c8766c-e2db-4ac2-8c4d-1a6612fd1816)

**Comment by mrlordziemniak** [comment]
i have same problem as above, how to fix this? i have two filters xiaomi 2 and 3H
