### ISSUE TITLE
Hide information above the name

### ISSUE THREAD

**Issue by Qu4Q** [denysdovhan/purifier-card#311]
**Is your feature request related to a problem? Please describe.**
Is there any way to hide the information above the name of the air purifier? I couldn't find anything like that in the documentation. This information is simply duplicated in my configuration and disturbs the aesthetics of my panel.

**Describe the solution you'd like**
Option to hide the entire top bar

**Describe alternatives you've considered**
Option to hide individual elements on the left or right side of the top bar or the whole thing

**Additional context**
![air](https://github.com/denysdovhan/purifier-card/assets/92187513/777ce68d-4d30-4ccb-845a-b87604f8134c)

**Comment by denysdovhan** [comment]
This is not yet possible.
