### ISSUE TITLE
Possibility to set any name for the air purifier.

### ISSUE THREAD

**Issue by Qu4Q** [denysdovhan/purifier-card#312]
**Is your feature request related to a problem? Please describe.**
I did not find any option in the documentation to change the display name of the air purifier. In my current configuration, the words "air purifier" are duplicated and it seems that apart from hiding the entire name, I can't do anything with it.

**Describe the solution you'd like**
Possibility to set any displayed name of the air purifier.

**Describe alternatives you've considered**
*none*

**Additional context**
![image](https://github.com/denysdovhan/purifier-card/assets/92187513/d0111c4a-5df2-4993-92d0-dea2fdf5c067)

**Comment by denysdovhan** [comment]
I think this might be a relevant feature. This should be easy to implement, would you like to do this?

**Comment by rappc87** [comment]
Click on the three dots, then click on the gear icon in the window that appears, and type what you want in the Name section.
