### ISSUE TITLE
How can I change the AQI value?

### ISSUE THREAD

**Issue by cloudy4125** [denysdovhan/purifier-card#342]
I'm using all the functions I want.
Thank you.
However, I want to change the AQI value in the middle of the image to sensor.zhimi_za1_59be_pm25_dense, but there is no example. Please help
![스크린샷 2024-04-16 220818](https://github.com/denysdovhan/purifier-card/assets/125760998/c303fa39-8483-4ca5-ab01-5e6b11d3936b)

**Comment by denysdovhan** [comment]
Read the docs: https://github.com/denysdovhan/purifier-card?tab=readme-ov-file#aqi-object
