### ISSUE TITLE
Set AQI by custom AQI Entity - Coway Airmega

### ISSUE THREAD

**Issue by tbase9** [denysdovhan/purifier-card#36]
I'm trying to add a custom AQI entity/attribute to set the AQI value for an Airmega 400S. Though when I add the AQI code into the card, all that changes is the "units".  The only entities in Hass that came from the IOCare integration were a fan, a switch, and an air_quality entity. The fan appears to be able to turn on and off the device, and also displays the filter levels and fan speed. The switch I have no idea what it does, and the air quality shows values in ug/m3 units.

I have posted the code below. I opened the issue in this repo since I didn't know where else to ask a question about this and I thought this may have been an issue with the card itself. Please let me know if any more information would be helpful or if there is another place to post this question.

```yaml
aqi:
   entity: air_quality.airmega400s
   attribute: air_quality_index
   unit: "ug/m3"
```

**Comment by mihsu81-hacs** [comment]
Hi @tbase9,

You should use _entity_id_ instead of _entity_.

aqi:
    entity_id: sensor.mb4_5ce50ca7e711_density
    attribute: Environmen pm2 5 density
    unit: µg/m³

![image](https://user-images.githubusercontent.com/84993041/127644406-5bb5ee7c-2726-46a2-b909-31310d944071.png)

**Comment by denysdovhan** [comment]
Already answered by @mihsu81-hacs. Thanks @mihsu81-hacs!
