### ISSUE TITLE
Update to new fan-model (aka: set_speed/speed_list is deprecated)

### ISSUE THREAD

**Issue by betaboon** [denysdovhan/purifier-card#39]
**Is your feature request related to a problem? Please describe.**

I am currently in the process of migrating https://github.com/betaboon/philips-airpurifier to the new fan-model and noticed this card didn't do that yet.

`set_speed` and `speed_list` is deprecated.

**Describe the solution you'd like**

Support `set_preset_mode` and `preset_modes`.

**Additional context**
https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties
https://github.com/home-assistant/core/pull/45407

**Comment by spider7611** [comment]
Yes please modify your card because can't use it now.

**Comment by spider7611** [comment]
Still isn't working for me.
`actions:
  - name: Auto
    icon: 'mdi:brightness-auto'
    speed: auto
  - name: Sleep
    icon: 'mdi:weather-night'
    speed: sleep`

**Comment by betaboon** [comment]
> Still isn't working for me.
> `actions:
> 
>     * name: Auto
>       icon: 'mdi:brightness-auto'
>       speed: auto
> 
>     * name: Sleep
>       icon: 'mdi:weather-night'
>       speed: sleep`

i think you need to replace `speed: auto` with `preset_mode: auto`

**Comment by spider7611** [comment]
If I changed all of icon highlight and not working.

`actions:
  - name: Auto
    icon: 'mdi:brightness-auto'
    preset_mode: auto
  - name: Sleep
    icon: 'mdi:weather-night'
    preset_mode: sleep`

**Comment by akarpych** [comment]
Doesn't work after all updates:
actions:
  - name: Silent
    icon: 'mdi:weather-night'
    preset_mode: Silent
  - name: 25%
    icon: 'mdi:circle-slice-2'
    preset_mode: Favorite
    xiaomi_miio_favorite_level: 3
  - name: 50%
    icon: 'mdi:circle-slice-4'
    preset_mode: Favorite
    xiaomi_miio_favorite_level: 7
  - name: 75%
    icon: 'mdi:circle-slice-6'
    preset_mode: Favorite
    xiaomi_miio_favorite_level: 10
  - name: 100%
    icon: 'mdi:circle-slice-8'
    preset_mode: Favorite
    xiaomi_miio_favorite_level: 14
  - name: Auto
    icon: 'mdi:brightness-auto'
    preset_mode: Auto
How to fix?
