### ISSUE TITLE
Add new device support - Smartmi Air Purifier

### ISSUE THREAD

**Issue by orionowy** [denysdovhan/purifier-card#46]
### Request Smartmi zhimi.airpurifer.za1 - Air Purifier support 
[](https://www.smartmiglobal.com/collections/air-purifier/products/smartmi-air-purifier
)

**Xiaomi App Detalis details:**

```
ID: 393002509
IP: 192.168.0.xx
MODEL: zhimi.airpurifer.za1
```

**Comment by denysdovhan** [comment]
Please, open a PR
Thanks for reporting!

**Comment by twhite96** [comment]
Can I open a PR for this? I have a Smartmi air purifier P2 and was looking for this integration.
