### ISSUE TITLE
Additional button and temp|hymid stats

### ISSUE THREAD

**Issue by atriumcarceri** [denysdovhan/purifier-card#47]
Please, add led brightness button right after power button. Tried to make it by myself, but it not rendered at all.
Second feature that purifier have own temp|humid sensons. It will be nice to show them right or left from aqi stat.

**Comment by denysdovhan** [comment]
Brightness buttons can be implemented [via `actions` object](https://github.com/denysdovhan/purifier-card#actions-object). Temperature and humidity can be displayed [via `stats` object](https://github.com/denysdovhan/purifier-card#stats-object).
