### ISSUE TITLE
Move the AQI

### ISSUE THREAD

**Issue by ads1230** [denysdovhan/purifier-card#55]
The main AQI display is in the middle of the GIF.
Is there a way to remove this? or shift it below the GIF?
You can add the air quality to the attribute section, but I can't find a way to disable the main AQI.

```  
- attribute: aqi
   unit: PM2.5
   subtitle: Air Quality
```

**Comment by denysdovhan** [comment]
Thanks for reaching out!

It's not possible at the moment. Should be easy to do. You can send a PR if you like to have this feature.
