### ISSUE TITLE
Cannot Select Xiaomi Air Purifier

### ISSUE THREAD

**Issue by johnjoemorgan** [denysdovhan/purifier-card#58]
**Before submitting a bug**

[X ] I updated to the latest version available
[ X] I cleared the cache of my browser

**Describe the bug**

The drop down selector for the Entity does not show the Xiaomi Air Purifier installed via Xiaomi Miot Auto integration with entity ID as: climate.XXXXXXXXX

I f I manually add the device in code editor the device name appears n the card but I cannot control the device itself.

**Steps to reproduce**

Have Xiaomi air purifier installed via Xiaomi Miit Auto add the Air Purifier card

**Expected behavior**
Being able to choose the climate entity and not just fan entities

**Comment by Swiftnesses** [comment]
Same, the latest version doesn't appear to work for me :/

**Comment by johnjoemorgan** [comment]
If I uninstall the card and reinstall 10.3 I get the correct purifier code in the card and not the incorrect air filter reference.

However, while the card and its options appear I have no control over the actual filter

**Comment by johnjoemorgan** [comment]
OK Found the cause of the problem.  I have my zhimi.airpurifier.mb3 purifiers integrated with Xiaomi Miio *AUTO* and not the core Xiaomi Miio component (the auto allows for non-cloud control)  The Auto version create entities for purifiers under the CLIMATE domain and not FAN.  The purifier fan  is looking only for fans and not climate devices.

Humidifiers were sectioned off into their own domain in the last update.  We should push the same for purifiers?

**Comment by johnjoemorgan** [comment]
Error caused by using Xiaomi Miio Auto integrate vs HA Xiaomi Miio core component.  Auto version places the device into CLIMATE domain and not the FAN domain expected by the card.
