### ISSUE TITLE
double fan on the card

### ISSUE THREAD

**Issue by smic717394** [denysdovhan/purifier-card#59]
Hi, the Purifier Card works great but for whatever reason, I get 2 fans on the Purifier Card. 

[](![fan](https://user-images.githubusercontent.com/7848043/126902533-bc67f313-3c2f-4c27-bf6e-88a82a45a818.jpg))**Before submitting a bug**

[ ] I updated to the latest version available
[ ] I cleared the cache of my browser

**Describe the bug**

**Steps to reproduce**

3. See error

**Expected behavior**

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [e.g. 0.2.0]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [e.g [0.109.4]](url)

**Comment by peto-klobuk** [comment]
Hi, I have the same issue.
![double_fan](https://user-images.githubusercontent.com/79093347/127311540-d7af1b7b-9d31-4109-b1ad-3548914907c9.png)

**Comment by wkethman** [comment]
Same here

**Comment by akarpych** [comment]
Same here

**Comment by denysdovhan** [comment]
This is `speed` and `preset_mode`. This issue should be resolved by #60
