### ISSUE TITLE
This is great. A few feature requests if possible.

### ISSUE THREAD

**Issue by julianrinaldi** [denysdovhan/purifier-card#6]
For Dyson Air Purifiers, multiple entities are made for each purifier. It creates a fan entity, and also an air_quality entity for some models or individual sensors for others, like sensor.aqi, sensor.filter_life. It would be nice if you can bring in data to the card from multiple entities since the AQI doesn't show up in your card because it's from a different entity. Another nice feature would be to be able to create toggle action buttons that will set a service from true to false. I can add the services to turn on night mode and auto mode and oscillation, but I would need to create separate action buttons to turn them off (back to false), which means twice as many buttons as ideal. Overall, this is a great card though! Thanks.

The Master Bedroom Air Purifier model I have is the Dyson TP04. It works with your card other than not displaying the AQI since it's located in a different entity. The Gym Air Purifier is a Dyson TP02. I haven't added it to your card yet, but it will have the same issue, and its filter life is also a separate sensor as well.

<img width="400" alt="CleanShot 2020-10-04 at 08 26 27@2x" src="https://user-images.githubusercontent.com/492435/95015648-09e84500-061c-11eb-8fc1-2f720e36712b.png">
<img width="400" alt="CleanShot 2020-10-04 at 08 26 40@2x" src="https://user-images.githubusercontent.com/492435/95015657-18cef780-061c-11eb-84c6-533e6c459982.png">
<img width="404" alt="CleanShot 2020-10-04 at 08 27 13@2x" src="https://user-images.githubusercontent.com/492435/95015662-1cfb1500-061c-11eb-9548-e912370243f0.png">
<img width="925" alt="CleanShot 2020-10-04 at 08 28 16@2x" src="https://user-images.githubusercontent.com/492435/95015665-21bfc900-061c-11eb-8d8a-8e50053c858d.png">
<img width="296" alt="CleanShot 2020-10-04 at 08 31 10@2x" src="https://user-images.githubusercontent.com/492435/95015670-2a180400-061c-11eb-9f92-97d1a0ee2182.png">

**Comment by wkethman** [comment]
You can do this in the current versions

Example
`type: custom:purifier-card
    entity: fan.winix_bedroom
    compact_view: true
    show_state: true
    stats:
      - entity_id: sensor.winix_bedroom
        unit: QV
        subtitle: Air quality
      - entity_id: sensor.winix_mode_bedroom
        subtitle: Mode
      - attribute: percentage
        unit: '%'
        subtitle: Fan speed`

**Comment by julianrinaldi** [comment]
Yes, thanks. I've been using this now for a while. Forgot to mark this as closed.
