### ISSUE TITLE
Xiaomi Air Purifier 3C custom support

### ISSUE THREAD

**Issue by luisleonardo** [denysdovhan/purifier-card#65]
**Describe the bug**
Since the Xiaomi Air Purifier 3C doesn't have native support, I am trying to add it manually.
I have all the information in the card from custom attributes, but there is no option to control the device with custom entities/attributes. From what I could find, this card is design to work with fan entities and not climate entities and that's the reason why it doesn't work.

Is there a way to control this device manually, or do I have to wait for native support?

I am using the following code:
`type: custom:purifier-card
entity: climate.air_purifier_air_purifier
aqi:
  attribute: environment.pm2_5_density
  unit: null
stats:
  - attribute: filter.filter_life_level
    unit: '%'
    subtitle: Filter Remaining
  - attribute: custom_service.moto_speed_rpm
    unit: RPM
    subtitle: Motor Speed
actions:
  - name: Sleep
    icon: mdi:weather-night
    speed: Sleep
  - name: Auto
    icon: mdi:brightness-auto
    speed: Auto
show_name: true
show_state: true
show_toolbar: true
compact_view: true`

**Steps to reproduce**
If you click the on/off, auto, sleep, etc. you get a spinning wheel like in the screenshot above.

**Expected behavior**
Turning the device on/off.

**Screenshots**
![image](https://user-images.githubusercontent.com/4042791/129919316-fb24ee05-f208-45e9-b0cf-84eaa32ff172.png)

**Versions:**
- Release: v0.11.1 and older versions
- Browser: Chrome or any other
- HomeAssistant version: core-2021.9.0.dev20210818 (but had the same issue with 2021.8)

**Comment by gfduszynski** [comment]
@foglietti Works nicely. I would suggest using "Insert code (ctrl+e)" for pasting config, it will maintain white space and make it much easier to copy :)

**Comment by foglietti** [comment]
@gfduszynski I have modified my comment. Thanks.

**Comment by denysdovhan** [comment]
`fan_set_favorite_level` is removed in the latest version of purifier-card. Hopefully this issue is resolved.
