### ISSUE TITLE
Feature request: ability to fire multiple service calls in toolbar actions

### ISSUE THREAD

**Issue by petercpg** [denysdovhan/purifier-card#67]
**Is your feature request related to a problem? Please describe.**

I have a Smartmi Air Purifier (zhimi.airpurifer.za1) which is not supported by official HA `xiaomi_miio` integration, https://github.com/syssi/xiaomi_airpurifier is used instead.

Some actions like changing fan levels requires two-step service calls:
- Change `preset_mode` to Favorite, if it is in other states
- Set desired fan level

Simply changing fan level does not change `preset_mode` together and `xiaomi_miio_favorite_level` in `actions` object seems doesn't work for me.

**Describe the solution you'd like**

Would be nice if this card provides ability to fire multiple service calls (as well as their service_data respectively), or this device-specified customization is considered.

**Describe alternatives you've considered**

My current workaround is to add another action to toolbar so I change preset_mode to Favorite first, then change fan level.

**Additional context**

**Comment by snp88** [comment]
Hi did you try fan.set_percentage service ??

**Comment by petercpg** [comment]
Nope - `fan.set_percentage` works for fans only, not for air purifier models

**Comment by snp88** [comment]
i have different model of the purifier and its show as fan in HA but maybe your model is different :)

**Comment by denysdovhan** [comment]
You can wrap multiple service calls under a single script.
