### ISSUE TITLE
Card takes too much space

### ISSUE THREAD

**Issue by Yersi88** [denysdovhan/purifier-card#74]
**Is your feature request related to a problem? Please describe.**

The card is too big, it takes too much space on the dashboard. 

**Describe the solution you'd like**
Make the card more compact, for example just changing the vertical dimension to something 'shorter'. There is a lot of wasted space there.

**Describe alternatives you've considered**
- Buttons from the bottom on side instead. 
- Eliminate power button by making the click on the card turn the thing on and off

**Additional context**
![image](https://user-images.githubusercontent.com/77145281/141779804-f4bf8b54-7492-4103-916f-01633159c8b2.png)
So much empty space on the card

**Comment by denysdovhan** [comment]
If you don't like this desing, I guess you have these options:

1. Try using `compact_view: true` options
2. Try changing `show_*` options in order to hide unnecessary info for you
3. Try using another card, like a built-in `entities` card.
