### ISSUE TITLE
Compatibility with RabbitAir MinusA2

### ISSUE THREAD

**Issue by oadslug** [denysdovhan/purifier-card#76]
Is there anyway to make this compatible with the RabbitAir Minus A2. From what I can gather the RA currently works with Amazon Alexa using a PIN provided by RabbitAir, but unfortunately that's where my knowledge ends. Any ideas would be much appreciated. Thank you!

**Comment by denysdovhan** [comment]
It's better to ask such question on HA community forum. This card only displays fans as purifiers. It doesn't integrate it with HA.

**Comment by oadslug** [comment]
Ok. Understood. Thank you. Will do. I apologize, I wasn't completely sure what the scope of this project was. Thanks again. Cheers.
