### ISSUE TITLE
AQI word over picture

### ISSUE THREAD

**Issue by JuhaFIN1** [denysdovhan/purifier-card#77]
In this last update v2.0.0 ( today) there is now AQI word over purifier picture and cannot change or remove it in code.

Purifier is: Philips ac2729, everythin else is working.

<img width="155" alt="aqi_Screenshot 2021-12-03 070051" src="https://user-images.githubusercontent.com/70380474/144548090-f5e2904c-ac5b-4bb2-b0b5-1075ca0d1106.png">

**Comment by JuhaFIN1** [comment]
Ok. So how do i get rid of it?

**Comment by denysdovhan** [comment]
You cannot. You have to manually provide an aqi object.

Though, it seems like a good option candidate to optionally hide aqi on the card.

**Comment by JuhaFIN1** [comment]
Yeah, i wote for it :) Or can you give me info how i can manually do aqi object :)

**Comment by noiwid** [comment]
Hi, 

I use a Mi Air Purifier 3H, and have exactly the same issue than @JuhaFIN1, I add my vote on the list :)

I found a sensor that seems report the expected data (sensor.mi_air_purifier_3_3h_pm2_5), but I can't find how to map it to the card. Any help would be welcomed  🙏

**Comment by NOTORIOUSVR** [comment]
> Edited.... Oh, I've finaly found on another topic how to solve this issue ! Just be careful to don't start the entity_id under aqi with a hyphen.

Thank you!!!

So frustrating that isn't isn't explained on the main page

**Comment by watzon** [comment]
Please add a way to hide this. I tried with the `style:` option, but it seems as though it's not possible that way.

**Comment by noiwid** [comment]
hi,
what are you tryin' to hide exactly?
