### ISSUE TITLE
Stats and AQI does not update realtime

### ISSUE THREAD

**Issue by mash2k3** [denysdovhan/purifier-card#79]
Stats and AQI does not update realtime, i have to do a browser refresh every time to update stats

**Comment by ostracizado** [comment]
...Or press a second time.
Then it updates the stats.

**Comment by Swiftnesses** [comment]
Same issue here. It worked at some stage :-/

**Comment by Mick51** [comment]
Same issue here. Still no fix for this problem ?

**Comment by psyhomb** [comment]
Same issue here, any updates?
