### ISSUE TITLE
Feature request: Option to hide AQI value over picture

### ISSUE THREAD

**Issue by gabrymed** [denysdovhan/purifier-card#80]
It is possible to add an option to hide the brown card with AQI value over picture?
![Inkedcard_LI](https://user-images.githubusercontent.com/57106603/147493079-187df1c2-3bd2-4060-922f-061d30659f30.jpg)

**Comment by Tockerz** [comment]
I would also like this feature to further compact the card, e.g:

![image](https://user-images.githubusercontent.com/36097410/148533895-0897d7ff-2ab1-48bb-b754-31ebeb877bd6.png)

**Comment by gabrymed** [comment]
> I would also like this feature to further compact the card, e.g. to look like this:
> 
> ![image](https://user-images.githubusercontent.com/36097410/148533895-0897d7ff-2ab1-48bb-b754-31ebeb877bd6.png)

For this, i think you can try 
compact_view: true

**Comment by Tockerz** [comment]
> > I would also like this feature to further compact the card, e.g. to look like this:
> 
> For this, i think you can try compact_view: true

Compact view only gets you to this view (e.g. AQI or the text box still in place):

![image](https://user-images.githubusercontent.com/36097410/148615522-7ffb89f6-8777-4250-bb6a-85098a616da5.png)

**Comment by MarkRMonaco** [comment]
I would also like to hide AQI as well.  Compact Mode doesn't hide it.

**Comment by gabrymed** [comment]
> I'm using a little bit trick is that using lovelace card mod and add code as below which not have to modify file and receive update as normally.
> 
> ```
> card_mod:
>   style: |
>     ha-card > div.preview > div.controls > div >div { 
>       visibility: hidden
> ```

Thanks for the advice

**Comment by Tockerz** [comment]
> I'm using a little bit trick is that using lovelace card mod and add code as below which not have to modify file and receive update as normally.
> 
> ```
> card_mod:
>   style: |
>     ha-card > div.preview > div.controls > div >div { 
>       visibility: hidden
> ```

Doesn't seem to have worked for me.

**Comment by caohuongls** [comment]
> > I'm using a little bit trick is that using lovelace card mod and add code as below which not have to modify file and receive update as normally.
> > ```
> > card_mod:
> >   style: |
> >     ha-card > div.preview > div.controls > div >div { 
> >       visibility: hidden
> > ```
> 
> Doesn't seem to have worked for me.
Here is how I add them
![image](https://user-images.githubusercontent.com/17307638/166106590-26ad6639-bbd6-4ca8-9db4-9772f80a8bb2.png)

**Comment by Tockerz** [comment]
Thanks for that. I realise now that it only works if compact mode is set to false. What I am really trying to do is remove that panel altogether as with my edited pic on Jan 7th.

**Comment by xbavnu** [comment]
> Thanks for that. I realise now that it only works if compact mode is set to false. What I am really trying to do is remove that panel altogether as with my edited pic on Jan 7th.

Have you found a solution to hide it?

**Comment by Shagon94** [comment]
You can use https://github.com/thomasloven/lovelace-card-mod with the above CSS, confirmed it works.

**Comment by karolx91** [comment]
> Thanks for that. I realise now that it only works if compact mode is set to false. What I am really trying to do is remove that panel altogether as with my edited pic on Jan 7th.

With card-mod you can hide every part of data. First you must conifgure card-mod (https://github.com/thomasloven/lovelace-card-mod). I hide PM2,5 and slider with this code:

>card_mod:
  style: |
    ha-card > div.preview > div.controls > div > div { 
      visibility: hidden}
    ha-card > div.preview > div.controls > div.slider > round-slider { 
      visibility: hidden}

<img width="722" alt="Zrzut ekranu_20221203_182327" src="https://user-images.githubusercontent.com/118118720/205453758-6ea84c80-8b3f-432a-93b5-7006881f2b04.png">

**Comment by Tockerz** [comment]
> With card-mod you can hide every part of data. First you must conifgure card-mod (https://github.com/thomasloven/lovelace-card-mod). I hide PM2,5 and slider with this code:

As with my previous post, this works fine in normal mode, but not in compact mode which is what I am trying to run.
WIth compact mode set to true, the card-mod hiding does not work - the AQI remains.

**Comment by karolx91** [comment]
> > With card-mod you can hide every part of data. First you must conifgure card-mod (https://github.com/thomasloven/lovelace-card-mod). I hide PM2,5 and slider with this code:
> 
> As with my previous post, this works fine in normal mode, but not in compact mode which is what I am trying to run. WIth compact mode set to true, the card-mod hiding does not work - the AQI remains.

In compact mode also works.

>    ha-card > div.preview > div.controls > div.current-aqi { 
      visibility: hidden}

<img width="719" alt="Zrzut ekranu_20221204_130810" src="https://user-images.githubusercontent.com/118118720/205489598-b8e3cf56-50d1-4ee4-8314-5a993a27ec8a.png">

**Comment by Tockerz** [comment]
Yes that works to hide AQI for me (thanks!!) but does not remove the dead space unfortunately. Don't suppose that is something card_mod can handle?

![image](https://user-images.githubusercontent.com/36097410/205526524-4f52e04f-586f-4628-bb95-4da53d8ac4ef.png)

**Comment by hflocki** [comment]
> card_mod:
> style: |
> ha-card > div.preview > div.controls > div > div {
> visibility: hidden}

I use it like this to minimize the gap

```
card_mod:
  style: |
    ha-card > div.preview > div.controls {
    visibility: hidden; height: 0px}
```

**Comment by Tockerz** [comment]
> I use it like this to minimize the gap
> 
> ```
> card_mod:
>   style: |
>     ha-card > div.preview > div.controls {
>     visibility: hidden; height: 0px}
> ```

This is the solution for me - thanks so much!
