### ISSUE TITLE
Trouble getting preset mode to switch, Failed to call service fan/set_preset_mode. {preset_mode} is not one of the valid preset modes: {self.preset_modes}

### ISSUE THREAD

**Issue by bobloadmire** [denysdovhan/purifier-card#81]
**Before submitting a bug**

[X ] I updated to the latest version available
[ X] I cleared the cache of my browser

**Describe the bug**

Trouble getting preset mode to switch, Failed to call service fan/set_preset_mode. {preset_mode} is not one of the valid preset modes: {self.preset_modes}

**Steps to reproduce**

my Levoit 400s exposes 2 preset modes "sleep" and "auto" trying to call either of those gives this error message, i've tried all caps, all lowercase, same error

**Expected behavior**
switch to preset mode

**Screenshots**
screenshot of available options:
https://imgur.com/G4I5esr

updated HA and HACS to latest available on everything.

Additionally, the card isn't picking up the air quality sensor for the AQI overlay, but I can call it in in the status bar no problem as "air_quality" is there an easy solution for this?

**Comment by siffup** [comment]
...same with my Aiibot 500.

**Comment by Siffup** [comment]
@bobloadmire 
about the air quality: you have to configure a sensor I calld it emission and add it to the card like this
stats:
  - entity_id: sensor.emission
    unit: µg/m³
    subtitle: Emmision
Preset modes not working here, too...

**Comment by hflocki** [comment]
> 
That work with my Levoit 300s
`shortcuts:
  - name: Auto
    icon: mdi:brightness-auto
    preset_mode: auto
  - name: Niedrig
    icon: mdi:circle-slice-2
    percentage: 33
  - name: Mittel
    icon: mdi:circle-slice-4
    percentage: 66
  - name: Hoch
    icon: mdi:circle-slice-8
    percentage: 100
  - name: Sleep
    icon: mdi:weather-night
    preset_mode: sleep`

I look for preset names here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/vesync/fan.py
