### ISSUE TITLE
Failed to call service fan/set_speed. extra keys not allowed @ data['0']

### ISSUE THREAD

**Issue by MarkRMonaco** [denysdovhan/purifier-card#84]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

I have a Levoit Core 200S air purifier (latest revision), which only has one "mode" exposed to the entity ("sleep").  Therefore, when I use automations, I have to call the service "fan.set_speed" so I can specify a speed by its name (sleep, low, medium, or high).  I have attempted to reproduce this in the Lovelace card, but receive an error when I press any of the buttons:  "Failed to call service fan/set_speed. extra keys not allowed @ data['0']".  This may not be actually a bug, but maybe a lack of understanding..

**Steps to reproduce**

See the screenshot showing my current YAML configuration.  Ignore the typo under the "Med" shortcut, as that has already been corrected. - Also, please ignore the current YAML code under the AQI section.

**Expected behavior**

I press the button for the specific speed I configured, and the air purifier switches to that speed without any errors.

**Screenshots**

![Screenshot_20220202-111939_Home Assistant](https://user-images.githubusercontent.com/52895653/152206999-c21d5eb6-706a-4de8-946b-e5b26efec49a.jpg)

![Screenshot_20220202-112235_Home Assistant_v2](https://user-images.githubusercontent.com/52895653/152211617-65530224-5b29-44fa-b519-aaf3e2367228.jpg)

**Versions:**
- Latest Home Assistant Core running as a docker container on my Unraid server.
- Latest 64-bit version of Google Chrome, or the Official Home Assistant Android app.

**Comment by MarkRMonaco** [comment]
I have worked around the issue by specifying speed percentages.

**Comment by bobloadmire** [comment]
> I have worked around the issue by specifying speed percentages.

this is the way
