### ISSUE TITLE
Paper Elements are being removed

### ISSUE THREAD

**Issue by vampywiz17** [denysdovhan/purifier-card#88]
Hello there,

This Breaking change is cause this in the card, on 2022.3:

https://developers.home-assistant.io/blog/2022/02/18/paper-elements/

![image](https://user-images.githubusercontent.com/14281430/156677927-f11e784f-00a1-4bc9-a9bd-e2f486759575.png)

I only mention it, not wait the solution... I think in this situation this thing is the last that the developer wants to deal with....

**Comment by Tockerz** [comment]
Definitely no expectation on the dev, please stay safe!

This element can be hidden for now with 'show_preset_mode: false' in config.

**Comment by BigWebstas** [comment]
I am also experiencing this issue
![image](https://user-images.githubusercontent.com/2896329/157094521-14533d13-7173-4ca2-8bd4-21ab8ca45a33.png)

**Comment by Unfocused** [comment]
Fixed in #90 and released in [v2.0.2](https://github.com/denysdovhan/purifier-card/releases/tag/v2.0.2)
