### ISSUE TITLE
Card not showing correctly on HA 2022.3

### ISSUE THREAD

**Issue by FrancYescO** [denysdovhan/purifier-card#89]
Mainly same of https://github.com/denysdovhan/vacuum-card/issues/338

**Comment by pilot173** [comment]
Same for me

**Comment by VSH0002** [comment]
same as me. the vacuum card already been fixed, but the purifier is yet to be done.

**Comment by anant418312** [comment]
same here

**Comment by dangnguyen0906** [comment]
same here :(

**Comment by nepozs** [comment]
It is related to #88 

Temporary workaround by @Tockerz:

> This element can be hidden for now with 'show_preset_mode: false' in config.

**Comment by Unfocused** [comment]
Fixed by #90 and released in [v2.0.2](https://github.com/denysdovhan/purifier-card/releases/tag/v2.0.2)
